### ISSUE TITLE
To position for Trinity

### ISSUE THREAD

**Issue by YoungSeng** [genea-workshop/Speech_driven_gesture_generation_with_autoencoder#2]
Hello, for https://github.com/genea-workshop/Speech_driven_gesture_generation_with_autoencoder/tree/c19f7f01a64c04df7432f20fe3c5b04311ba5ac1, is the `_to_pos `function in its `preprocessing.py` in `pymo` not working, because I can't get it to work successfully using `('param', MocapParameterizer('position'))` in the pipeline.

I also ask this question in https://github.com/youngwoo-yoon/Co-Speech_Gesture_Generation/issues/13, I hope you can help me take a look, thank you!

**Comment by TeoNikolov** [comment]
> Hello, for https://github.com/genea-workshop/Speech_driven_gesture_generation_with_autoencoder/tree/c19f7f01a64c04df7432f20fe3c5b04311ba5ac1, is the `_to_pos `function in its `preprocessing.py` in `pymo` not working, because I can't get it to work successfully using `('param', MocapParameterizer('position'))` in the pipeline.
> 
> 
> 
> I also ask this question in https://github.com/youngwoo-yoon/Co-Speech_Gesture_Generation/issues/13, I hope you can help me take a look, thank you!

Can you share a crash log and code that you are using? I may not be able to help directly, but I believe this information will be useful to figure out a solution.

**Comment by YoungSeng** [comment]
Okay, thank you, I uploaded my code [here](https://github.com/YoungSeng/Pymo-Issue). For the `TestSeq001.bvh` file in the GENEA validation set, there are 71 joints in the whole body, minus 14 joints with `Nub`, leaving 57 joints, the coordinates of its position should be 171, but only 162 after conversion, what should I do?

**Comment by TeoNikolov** [comment]
I propose we close the issue in this repository, and track it at https://github.com/youngwoo-yoon/Co-Speech_Gesture_Generation/issues/13 instead, to keep all information in one place.

I don't have collaboration access to this repo, so maybe you (@YoungSeng) or @Svito-zar could close it.
